# Generated by Django 4.2.10 on 2024-04-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0012_alter_languageinfo_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
